const affirmations = [
    "You are enough just as you are.",
    "Your hard work and dedication are paying off.",
    "You have a heart of gold.",
    "You inspire me to be a better person.",
    "You are so talented and capable.",
    "I appreciate everything you do for me.",
    "You have a great sense of humor.",
    "You make a difference in the world.",
    "You are a wonderful friend.",
    "Your kindness and compassion are admirable.",
    "You have a beautiful smile.",
    "You are loved and appreciated.",
    "You are a great listener.",
    "Your creativity is impressive.",
    "You are strong and resilient.",
    "You are intelligent and insightful.",
    "Your positive attitude is infectious.",
    "You are brave and courageous.",
    "You have a way of making others feel special.",
    "You are an inspiration to others.",
    "You are a true gift to those around you.",
    "You are a fantastic problem-solver.",
    "You have a great work ethic.",
    "Your dedication to your goals is impressive.",
    "You have a unique perspective on things.",
    "You are a great leader.",
    "You have a contagious enthusiasm.",
    "You are making a difference in the world.",
    "You have a heart of service.",
    "Your contributions are valued and appreciated.",
    "You have a great sense of style.",
    "Your attention to detail is impressive.",
    "You have a great sense of humor that lifts people's spirits.",
    "You have a way of making others feel seen and heard.",
    "You have a beautiful spirit.",
    "You have a positive impact on the people around you.",
    "You are a great communicator.",
    "You have a natural talent for kindness.",
    "You have a unique and valuable perspective.",
    "You have a magnetic personality.",
    "You are a quick learner.",
    "You have a heart for serving others.",
    "You are a great problem solver.",
    "You have an infectious smile.",
    "You have a contagious positive energy.",
    "You have a great sense of humor that can make anyone laugh.",
    "You have a big heart and a generous spirit.",
    "You have a special talent for kindness.",
    "You have a beautiful soul.",
    "You are a wonderful role model.",
    "You have a great attitude.",
    "You have an incredible work ethic.",
    "You have a unique and valuable perspective on life.",
    "You have a heart for helping others.",
    "You have a natural talent for making people feel comfortable.",
    "You have a way of making everyone feel included.",
    "You have a beautiful way with words.",
    "You are an amazing listener.",
    "You have a wonderful laugh that can brighten up anyone's day.",
    "You have a special way of showing kindness.",
    "You are an incredible friend.",
    "You have a heart for making a difference.",
    "You have a great sense of humor that can turn any situation around.",
    "You have a magnetic personality that draws people to you.",
    "You have a natural talent for leadership.",
    "You have a beautiful singing voice.",
    "You have a great way of handling difficult situations.",
    "You have a way of making people feel loved.",
    "You are an amazing parent.",
    "You have a natural talent for making people feel understood.",
    "You have a unique and creative approach to problem-solving.",
    "You have a way of making everyone feel welcome.",
    "You are incredibly thoughtful and caring.",
    "You are a true gem.",
    "You have a heart of pure gold.",
    "You are a bright light in the world.",
    "You have a contagious zest for life.",
    "You have an unbreakable spirit.",
    "You are a beacon of hope for those around you.",
    "You have a heart for justice and equality.",
    "You have a unique and powerful voice.",
    "You have an eye for beauty and detail.",
    "You have a heart for adventure and exploration.",
    "You have a contagious love for learning.",
    "You have a way of making the impossible possible.",
    "You are a master at turning challenges into opportunities.",
    "You are a natural born leader.",
    "You have a heart for making the world a better place.",
    "You have a contagious enthusiasm for life.",
    "You have a unique and valuable perspective on the world.",
    "You have a way of lifting people's spirits.",
    "You have a heart for animals and the environment.",
    "You have a magnetic personality that draws people to you.",
    "You have a way of making people feel safe and secure.",
    "You have an incredible sense of humor that brightens everyone's day.",
    "You have a heart of compassion and empathy.",
    "You have a natural talent for teaching and mentoring.",
    "You have a unique ability to connect with people from all walks of life.",
    "You have a contagious sense of curiosity.",
    "You have a heart for serving others selflessly.",
    "You have a way of making people feel heard and understood.",
    "You have a creative and innovative mind.",
    "You have a heart for community and connection.",
    "You have a unique and creative approach to problem-solving.",
    "You have a contagious spirit of generosity.",
    "You have an incredible sense of style.",
    "You have a way of making people feel like they belong.",
    "You have a heart for spreading kindness and love.",
    "You have a natural talent for bringing people together.",
    "You have a magnetic energy that fills the room.",
    "You have a way of making people feel appreciated and valued.",
    "You have a heart for healing and restoration.",
    "You have a unique and valuable skill set.",
    "You have a contagious spirit of gratitude.",
    "You have an incredible work ethic that inspires others.",
    "You have a way of making people feel like they can do anything.",
    "You have a heart for creativity and self-expression.",
    "You have a natural talent for making people feel uplifted.",
    "You have a magnetic presence that commands attention.",
    "You have a way of making people feel at ease.",
    "You have a heart for making a difference in the world.",
    "You have a unique and inspiring story to tell.",
    "You have a contagious sense of adventure.",
    "You have an incredible sense of intuition.",
    "You have a way of making people feel like they are part of something bigger.",
    "You have a heart for growth and personal development.",
    "You have a natural talent for making people feel seen and heard.",
    "You have a magnetic charisma that draws people to you.",
    "You have a way of making people feel empowered and confident.",
    "You have a heart for making meaningful connections with others.",
    "You have a unique and powerful purpose in life.",
    "You have a contagious sense of wonder.",
    "You are capable of achieving great things.",    "You have the power to overcome any challenge.",    "You possess unique talents and abilities that make you special.",    "You are worthy of love and respect.",    "You are deserving of happiness and fulfillment.",    "You are a valuable member of your community.",    "You have the potential to make a positive impact on the world.",    "You are intelligent and capable of learning and growing.",    "You are a work in progress, and that's okay.",    "You have the ability to create the life you want.",    "You are in control of your own happiness and success.",    "You are enough, just as you are.",    "You are loved and appreciated for who you are.",    "You have the power to change your thoughts and beliefs.",    "You are worthy of all the good things that come your way.",    "You have a purpose in this world.",    "You are surrounded by love and support.",    "You are beautiful, inside and out.",    "You are constantly evolving and improving.",    "You have the strength to overcome any obstacle.",    "You are a unique and valuable individual.",    "You have the ability to create positive change in your life.",    "You are capable of achieving your dreams.",    "You are strong and resilient.",    "You are worthy of respect and admiration.",    "You have the power to make a difference.",    "You are an important and integral part of the universe.",    "You are constantly learning and growing.",    "You are capable of handling whatever comes your way.",    "You are surrounded by abundance and prosperity.",    
    "You have a bright and prosperous future ahead of you.",
];  

function getRandomAffirmation() {
    const randomIndex = Math.floor(Math.random() * affirmations.length);
    return affirmations[randomIndex];
}

let output = getRandomAffirmation;

module.exports = output;

